Config = {}

--List of keys : https://docs.fivem.net/docs/game-references/controls/#controls
Config.Getupkey = 73

--key is prop name
--Value can have the following values : 
---- o = vec3 with the offset from object position to sitting position. +x is left, -y is  front, +z is up. can be vec3 or table of vec3
---- h = float heading correction for the sitting position relative to the object's
Config.Seats = {
    ['apa_mp_h_din_chair_09']={o = vec3(0.0, 0.25, 0.5)},
    ['apa_mp_h_din_chair_12']={},
    ['apa_mp_h_stn_chairarm_02']={o = vec3(0.0, -0.5, 0.5)},
    ['apa_mp_h_stn_chairarm_03']={o = vec3(0.0, -0.25, 0.5)},
    ['apa_mp_h_stn_chairarm_24']={},
    ['apa_mp_h_stn_chairstrip_07']={},
    ['apa_mp_h_stn_sofa2seat_02']={},
    ['apa_mp_h_yacht_sofa_01']={},
    ['apa_mp_h_yacht_sofa_02']={},
    ['ba_prop_battle_club_chair_03']={o = vec3(0.0, 0.0, -0.1)},
    ['bkr_prop_biker_chair_01']={},
    ['bkr_prop_weed_chair_01a']={},
    ['bkr_prop_biker_boardchair01']={o = vec3(0.0, 0.0, -0.1)},
    ['ex_mp_h_din_chair_12']={},
    ['ex_mp_h_off_sofa_01']={},
    ['ex_mp_h_off_sofa_02']={},
    ['ex_mp_h_stn_chairstrip_010']={},
    ['ex_prop_offchair_exec_01']={o = vec3(0.0, 0.0, -0.1)},
    ['ex_prop_offchair_exec_02']={o = vec3(0.0, 0.0, -0.1)},
    ['ex_prop_offchair_exec_03']={o = vec3(0.0, 0.0, -0.1)},
    ['ex_prop_offchair_exec_04']={o = vec3(0.0, 0.0, -0.1)},
    --['hei_heist_stn_benchshort']={},-- A l'envers dans la prison BCSO
    ['hei_heist_stn_sofa2seat_02']={},
    ['hei_heist_stn_sofa2seat_03']={},
	['hei_prop_heist_off_chair']={},
	['hei_prop_hei_skid_chair']={},
	['hei_prop_yah_seat_01']={},
	['hei_prop_yah_seat_02']={},
	['hei_prop_yah_seat_03']={},
    ['imp_prop_impexp_offchair_01a']={o = vec3(0.0, 0.0, -0.1)},
	['miss_rub_couch_01']={},
	['prop_armchair_01']={},
	['prop_bench_01a']={},
	['prop_bench_01b']={},
	['prop_bench_01c']={},
	['prop_bench_02']={},
	['prop_bench_03']={},
	['prop_bench_04']={},
	['prop_bench_05']={},
	['prop_bench_06']={},
	['prop_bench_07']={},
	['prop_bench_08']={},
	['prop_bench_09']={},
	['prop_bench_10']={},
	['prop_bench_11']={},
	['prop_chair_01a']={},
	['prop_chair_01b']={},
	['prop_chair_02']={},
	['prop_chair_03']={},
	['prop_chair_04a']={},
	['prop_chair_04b']={},
	['prop_chair_05']={},
	['prop_chair_06']={},
	['prop_chair_07']={},
	['prop_chair_08']={},
	['prop_chair_09']={},
	['prop_chair_10']={},
	['prop_chateau_chair_01']={},
	['prop_clown_chair']={},
	['prop_cs_office_chair']={},
	['prop_direct_chair_01']={o = vec3(0.0, 0.0, -0.0)},
	['prop_direct_chair_02']={o = vec3(0.0, 0.0, -0.0)},
	['prop_fib_3b_bench']={o = {
		vec3(1.0, 0.0, 0.5),
		vec3(-1.0, 0., 0.5),
		vec3(0.0, 0.0, 0.5),
	}},
	['prop_gc_chair02']={o = vec3(0.0, 0.0, -0.1)},
	['prop_hobo_seat_01']={},
	['prop_ld_bench01']={},
	['prop_ld_farm_chair01']={},
	['prop_off_chair_01']={},
	['prop_off_chair_03']={},
	['prop_off_chair_04']={},
	['prop_off_chair_04b']={},
	['prop_off_chair_04_s']={},
	['prop_off_chair_05']={},
	['prop_old_deck_chair']={},
	['prop_old_wood_chair']={},
	['prop_patio_lounger1']={o = vec3(0.0, -0.25, 0.35), s='PROP_HUMAN_SEAT_SUNLOUNGER'},
	['prop_rock_chair_01']={},
	['prop_skid_chair_01']={},
	['prop_skid_chair_02']={},
	['prop_skid_chair_03']={},
	['prop_sol_chair']={},
	['prop_table_01_chr_a']={},
	['prop_table_01_chr_b']={o = vec3(-0.1, 0.0, 0.0), h=90},
	['prop_table_02_chr']={},
	['prop_table_03b_chr']={},
	['prop_table_03_chr']={},
	['prop_table_04_chr']={},
	['prop_table_05_chr']={},
	['prop_table_06_chr']={},
	['prop_wheelchair_01']={},
	['prop_wheelchair_01_s']={},
	['prop_torture_ch_01']={},
	['prop_waiting_seat_01']={},
	['prop_yacht_seat_01']={},
	['prop_yacht_seat_02']={},
	['prop_yacht_seat_03']={},
	['prop_rub_couch01']={},
	['prop_ld_farm_couch01']={},
	['prop_ld_farm_couch02']={},
	['prop_roller_car_01']={},
	['prop_roller_car_02']={},
	['prop_rub_couch02']={},
	['prop_rub_couch03']={},
	['prop_rub_couch04']={},
	['prop_wait_bench_01']={},
	['p_armchair_01_s']={},
	['p_clb_officechair_s']={},
	['p_dinechair_01_s']={},
	['p_ilev_p_easychair_s']={},
	['p_soloffchair_s']={},
	['p_lev_sofa_s']={},
	['p_res_sofa_l_s']={},
	['p_v_med_p_sofa_s']={},
	['p_yacht_chair_01_s']={},
	['p_yacht_sofa_01_s']={},
    ['v_corp_lazychair']={},
    ['v_corp_facebeanbagd']={},
    ['v_serv_bs_barbchair2']={o = vec3(0.0, 0.0, 0.8)},
    ['v_serv_bs_barbchair3']={o = vec3(0.0, 0.0, 0.8)},
    ['v_serv_bs_barbchair5']={o = vec3(0.0, 0.0, 0.8)},
	['v_club_stagechair']={},
	['v_club_officechair']={},
	['v_corp_bk_chair3']={},
	['v_corp_cd_chair']={},
	['v_corp_offchair']={},
	['v_ilev_chair02_ped']={o = vec3(0.0, 0.0, -0.1)},
	['v_ilev_hd_chair']={},
	['v_ilev_p_easychair']={},
	['v_ret_gc_chair03']={},
	['v_ilev_leath_chr']={},
	['v_ilev_fh_dineeamesa']={},
	['v_ilev_fh_kitchenstool']={},
	['v_ilev_tort_stool']={},
	['v_ilev_m_sofa']={},
    ['v_med_whickerchair1']={o = vec3(0.0, 0.0, 0.0)},
    ['v_med_p_easychair']={},
	['v_med_hospseating1']={o = {
		vec3(0.0, 1.1, 0.0),
		vec3(0.0, 0.35, 0.0),
		vec3(0.0, -0.35, 0.0),
		vec3(0.0, -1.1, 0.0),
	}, h=90},
    ['v_med_p_sofa']={},
	['v_res_tre_sofa_s']={},
	['v_ret_gc_chair01']={o = vec3(0.0, 0.1, 0.37)},
	['v_tre_sofa_mess_a_s']={},
	['v_tre_sofa_mess_b_s']={},
	['v_tre_sofa_mess_c_s']={},
    ['v_res_kitchnstool']={o = vec3(0.0, 0.0, 0.7)},
	['v_ret_gc_chair02']={o = vec3(0.0, 0.0, -0.1)},
	['v_serv_ct_chair02']={o = vec3(0.0, 0.0, -0.1)},
	['xm_lab_sofa_02']={},
	['xm_lab_chairarm_12']={},
	['xm_prop_x17_avengerchair_02']={o = vec3(0.0, 0.0, -0.1)},
}
